version: '3'

services:
  app:
    build:
      context: ./
      dockerfile: ./docker/app.Dockerfile
    volumes:
      - ./:/var/www/html
  web:
    build:
      context: ./
      dockerfile: ./docker/web.Dockerfile
    links:
      - app
    ports:
      - 8000:80
  mysql:
    image: mysql:5.6
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: "secret"
      MYSQL_DATABASE: "homestead"
    volumes:
      - ./docker/data/mysql:/var/lib/mysql
